### PR TITLE
Additional StampedLockWithRetriesSpaceship with spin on optimistic read

### PR DESCRIPTION
**Pull request by storozhukBM**
Let's find out what the results would be?

I've made some tests in my [develop branch](https://github.com/storozhukBM/rw-concurrency/tree/develop/data). But it seems that dual core machine isn't enough for such tests, because the results for 2 writers and 2 readers look [strange](https://github.com/storozhukBM/rw-concurrency/blob/develop/data/results-i7-I7-5557U-OSX-Java-1.8.0_102-x64.pdf).

### CODE REVIEW

**Comment by mjpt777** [comment]
What is the goal you are trying to achieve?

**Comment by storozhukBM** [comment]
I'm currently writing thread save analog of [EvictingQueue](http://google.github.io/guava/releases/16.0/api/docs/com/google/common/collect/EvictingQueue.html) and trying to pick locking primitive for this task. 

I've found this great [blog post](http://mechanical-sympathy.blogspot.ru/2013/08/lock-based-vs-lock-free-concurrent.html) (thank you for it) and it has been basically what I was looking for, except one additional [implementation](https://github.com/storozhukBM/rw-concurrency/blob/master/src/StampedLockWithRetriesSpaceship.java) I'd try.

The main idea is the same as in Biased Locking. We trying to spin around optimistic read with hope that write lock won't take long and we will be able to read value few cycles later without acquiring real read lock. In theory if our code between `tryOptimisticRead()` and `validate()` is short enough we should have good chances of optimistic read case. It would lead to higher `writes/sec` rate without big degradation of `read/sec` rate.
I've tried to check this scenario on my machine. 
Results for `1r/1w`, `2r/1w` and `3r/1w` are close to my expectations. But result for `2r/2w` looks very weird (`read/sec` rate is too high).
So I thought maybe you would have time to look through the code/results and share your thoughts about it.

Thank you in advance for your answer.

**Comment by mjpt777** [comment]
Here are the results on a 4 core machine with hyper threading enabled.

https://github.com/mjpt777/rw-concurrency/blob/master/data/results-i7-3632QM-Linux-4.8.0-Java-1.8.0_102-x64.txt

**Comment by storozhukBM** [comment]
Thank you for your help @mjpt777.
I've used your benchmark results to create this [report](https://github.com/storozhukBM/rw-concurrency/blob/develop/data/results-i7-3632QM-Linux-4.8.0-Java-1.8.0_102-x64.pdf).
Few unexpected things in this results:
* `ReentrantLockSpaceship` shows the best result among all locks in cases `2r/1w` and `3r/1w`
* `StampedLockWithRetriesSpaceship` has even better throughput than `LockFreeSpaceship` in case of `2r/2w`

**Comment by mjpt777** [comment]
The significant thing those results don't show is the latency distribution. It would be good to redo them with JMH and get a latency distribution as well as a throughput benchmark. The tests are old and not as representative as they could be with JMH, so I'd be cautious about drawing too many conclusions.

**Comment by storozhukBM** [comment]
Can I use https://github.com/real-logic/benchmarks as the reference to create such tests?

**Comment by mjpt777** [comment]
It is a start but not the right fit. I'd use JMH thread groups for the readers and writers in this case.

**Comment by storozhukBM** [comment]
OK, thank you for the suggestions, I'll try to implement such tests and create separate PR.

**Pull request merged**
